#ifndef WROCLAW_UNIVERSITY_OF_SCIENCE_CODING_AND_DATA_COMPRESSION_LIST3_INC_CODINGTYPE_H_
#define WROCLAW_UNIVERSITY_OF_SCIENCE_CODING_AND_DATA_COMPRESSION_LIST3_INC_CODINGTYPE_H_

#include <unordered_map>
#include <iostream>
#include <fstream>

/**
 * Types of coding
 */
enum CodingType {
  GAMMA,
  DELTA,
  OMEGA,
  FIBONACCI
};

#endif //WROCLAW_UNIVERSITY_OF_SCIENCE_CODING_AND_DATA_COMPRESSION_LIST3_INC_CODINGTYPE_H_
