// autor - Jakub Drzewiecki

#ifndef WROCLAW_UNIVERSITY_OF_SCIENCE_1_SEM_LIST_4_EX_2_FUNS_H_
#define WROCLAW_UNIVERSITY_OF_SCIENCE_1_SEM_LIST_4_EX_2_FUNS_H_

void mastermind();

#endif //WROCLAW_UNIVERSITY_OF_SCIENCE_1_SEM_LIST_4_EX_2_FUNS_H_
